#!/bin/bash

echo "🚀 Learning Platform Deployment Guide"
echo "====================================="
echo ""

echo "📋 Prerequisites:"
echo "1. GitHub account"
echo "2. Vercel account (vercel.com)"
echo "3. Render account (render.com)"
echo ""

echo "📁 Step 1: Push to GitHub"
echo "-------------------------"
echo "1. Create a new GitHub repository"
echo "2. Run these commands:"
echo "   git init"
echo "   git add ."
echo "   git commit -m 'Initial commit'"
echo "   git branch -M main"
echo "   git remote add origin https://github.com/YOUR_USERNAME/learning-website.git"
echo "   git push -u origin main"
echo ""

echo "🌐 Step 2: Deploy Backend to Render"
echo "-----------------------------------"
echo "1. Go to render.com and sign up/login"
echo "2. Click 'New Web Service'"
echo "3. Connect your GitHub repository"
echo "4. Configure settings:"
echo "   - Name: learning-platform-backend"
echo "   - Root Directory: server"
echo "   - Runtime: Node"
echo "   - Build Command: npm install"
echo "   - Start Command: npm start"
echo "5. Add Environment Variables:"
echo "   NODE_ENV=production"
echo "   PORT=10000"
echo "   JWT_SECRET=your-super-secure-production-secret-key"
echo "   CLIENT_URL=https://your-frontend-url.vercel.app"
echo "6. Click 'Create Web Service'"
echo ""

echo "⚡ Step 3: Deploy Frontend to Vercel"
echo "------------------------------------"
echo "1. Go to vercel.com and sign up/login"
echo "2. Click 'New Project'"
echo "3. Import your GitHub repository"
echo "4. Configure settings:"
echo "   - Framework Preset: Create React App"
echo "   - Root Directory: client"
echo "   - Build Command: npm run build"
echo "   - Output Directory: build"
echo "5. Add Environment Variable:"
echo "   REACT_APP_API_URL=https://your-backend-url.onrender.com"
echo "6. Click 'Deploy'"
echo ""

echo "🔗 Step 4: Update URLs"
echo "----------------------"
echo "1. Copy your Render backend URL"
echo "2. Update Vercel environment variable REACT_APP_API_URL"
echo "3. Copy your Vercel frontend URL"
echo "4. Update Render environment variable CLIENT_URL"
echo ""

echo "✅ Step 5: Test Deployment"
echo "-------------------------"
echo "1. Test registration/login"
echo "2. Test course content"
echo "3. Test analytics export"
echo "4. Test all features"
echo ""

echo "🎉 Deployment Complete!"
echo "======================"
echo "Frontend: https://your-app.vercel.app"
echo "Backend: https://your-app.onrender.com"
echo ""
echo "Happy learning! 📚" 